services:
  db:
    image: mysql:latest
    restart: always
    container_name: todolist-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: mysqld
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  nginx:
    build:
      context: ../todolist-front/
      dockerfile: Dockerfile
    ports:
      - "80:80"

  php:
    build:
      context: ../todolist-back/
      dockerfile: Dockerfile
    ports:
      - "7564:80"
    volumes:
      - ../todolist-back/src:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
volumes:
  mysql-data:
