services:
  db:
    image: dhi.io/mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: